blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/ajayi-joseph/react-native-session-timeout/discussions
    about: For questions and general help, please use GitHub Discussions.
